server:
  port: 21001

spring:
  application:
    name: SERVICE-ORDER
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3309/springcloud-alibaba-order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimeZone=Asia/Shanghai
    username: root
    password: Root123;

management:
  endpoints:
    web:
      exposure:
        include='*'
